### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by simcrack** [urbans0ft/fclip#10]
There is a memory leak (1M) because of a missing delete:

https://github.com/urbans0ft/fclip/blob/ffd7947fe392fa9ceb1777f793af5abeb2c11429/src/fclip.cpp#L213C4-L213C30

**Comment by urbans0ft** [comment]
Strictly speaking you're right and this is not the only _missing_ `delete`. But the "leaks" are not serious at all:

> In modern operating systems, normal memory used by an application is released when the application terminates. This means that a memory leak in a program that only runs for a short time may not be noticed and is rarely serious.
> --[wikipedia](https://en.wikipedia.org/wiki/Memory_leak#Consequences)

To be honest, I deliberately decided not to release the memory, because after each execution the program and thus the process terminates and Windows releases the memory _for me_.
